# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - plt-ccr-v5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Sección de Build y Test Local (Recomendada, pero no obligatoria)
      - name: Create and Start virtual environment and Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          # Nota: Esta instalación aquí solo verifica que las dependencias existan.
          # La instalación real en Azure la hace Oryx.
          pip install -r requirements.txt
          
      # Carga del artefacto de despliegue
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/
            
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # CORRECCIÓN CLAVE: Aumentar el timeout del job para el proceso largo de Oryx Build en Azure.
    timeout-minutes: 45 
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_01B25303C0314DFAAC6CC5BB3FF0A355 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_50B1EF698AD34AAEA121539F864B7DEC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5CACEAA92C9245F987257AA65BCA05C8 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'plt-ccr-v5'
          slot-name: 'Production'
